project:
  type: website

website:
  title: "Miho Terahata"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        href: projects.qmd
      - text: Skills
        href: skills.qmd
      - text: Contact
        href: contact.qmd
