project:
  type: website
  output-dir: docs    # 👈 Required for GitHub Pages to find your site

website:
  title: "Miho's Portfolio"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        href: projects.qmd
      - text: Skills
        href: skills.qmd
      - text: Contact
        href: contact.qmd
